packages:
  - "apps/*"
  - "packages/*"
catalog:

  # Dev tooling
  eslint: ^9.23.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.15
  typescript: ^5.8.2

  # Database
  drizzle-orm: ^0.44.2

  # Misc
  zod: ^3.24.2

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.71.1
  "@trpc/client": ^11.1.0
  "@trpc/tanstack-react-query": ^11.1.0
  "@trpc/server": ^11.1.0

  react-hook-form: ^7.54.2
  "@hookform/resolvers": ^4.1.3