version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: vit-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Upstash-compatible HTTP Redis proxy
  upstash-proxy:
    image: hiett/serverless-redis-http:latest
    container_name: vit-upstash-proxy
    ports:
      - "8080:80"
    environment:
      - SRH_MODE=env
      - SRH_TOKEN=token
      - SRH_CONNECTION_STRING=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test:
        ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
    driver: local
